### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bharath-b-rh**
Removed $ from each of the command, to copy and use commands as is.

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by darshan-nagaraj** [comment]
@bharath-b-rh It's a standard convention in Openshift docs to mention about normal user($) and root user (#). We don't mention in the prerequisites section that user should be either "$" or "#". 

Also, I would like to mention that if you use **copy to clipboard** icon from docs.openshift.com, it will copy only command and excludes "$" or "#".

**Comment by bharath-b-rh** [comment]
@darshan-nagaraj Few of the openshift repositories did not have the commands with the prompt symbol, but if majority doesn't follow this convention, then better to have it standard way.
I will remove the changes and just have [this](https://github.com/openshift/node-observability-operator/pull/47/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R58) correcting the file name in command.

**Pull request merged**
