### PR TITLE
SCC agent: strengthen user and fsgroup

### PR DESCRIPTION
**Pull request by alebedev87**
Reading/writing from/into CRIO socket is admitted by DAC (via groupID) and by MAC(thanks to privileged container). Therefore no need to let the agent image set any uid or fsgroup.

### CODE REVIEW

**Comment by alebedev87** [comment]
> "e2e-gcp" post steps failed: "e2e-gcp" pod "e2e-gcp-gather-gcp-console" failed: the pod ci-op-mwx9xry6/e2e-gcp-gather-gcp-console was deleted without completing after 1m10s

/retest

**Comment by thejasn** [comment]
/label docs-approved
/label px-approved

Updates to stricken scc permissions attached to the agent. Docs and px review not required.

**Pull request merged**
