### PR TITLE
Add negative UTs for NOMC

### PR DESCRIPTION
**Pull request by bharath-b-rh**
ok  	github.com/openshift/node-observability-operator/pkg/operator/controller/machineconfig	4.525s	coverage: 92.5% of statements
?   	github.com/openshift/node-observability-operator/pkg/operator/controller/machineconfig/machineconfigfakes	[no test files]

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Awesome, LGTM!
/retest

**Comment by lmzuccarelli** [comment]
@bharath-b-rh - this is really a great effort. Great work Bharat

**Comment by lmzuccarelli** [comment]
Looks like there is a unit test failure

 ```
--- FAIL: TestReconcileClientFakes/logger_init_failure (0.00s)
        controller_test.go:1380: Reconcile() err: <nil>, wantErr: true
```

**Pull request merged**
